### ISSUE TITLE
Are the AWS Resources disposed of after the load test is completed?

### ISSUE THREAD

**Issue by TruffleMuffin** [goadapp/goad#1]
I looked through the code (but am not that familiar with Go) but I can't see anything that deletes the created resources after the testing has finished. Do the Lamda functions and SQS queues get deleted afterwards?

**Comment by jcxplorer** [comment]
There are four resources that get created:

- An IAM Role for the lambda function.
- An IAM Role Policy that allows the lambda function to send messages to SQS and publish logs.
- A lambda function.
- An SQS queue for the test.

After the test run it automatically deletes the SQS queue, but not the lambda function or IAM resources so that they can be reused for other tests. They don't incur any charges, but do make tests start faster.

We'll probably add a destroy command of some sort to delete everything.

**Comment by Integralist** [comment]
it would be good if this could be clearly documented in the README for now though

**Comment by jcxplorer** [comment]
This is now documented in the README, and I've added #20 to track adding a command for removing all goad related AWS resources.
